version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./css:/usr/share/nginx/html/css
      - ./js:/usr/share/nginx/html/js
      - ./data:/usr/share/nginx/html/data
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
